### ISSUE TITLE
How does one convert a Key into a HotKey?

### ISSUE THREAD

**Issue by Krutonium** [kirmir/GlobalHotKey#1]
For example, `GHot.Register(Keys.A)` doesn't work (Visual Basic jsyk), but how would this be done? Also, I need to hook a Key, who's Keycode is 255, and described according to windows as `LButton, OemClear`, how would I do this?

**Comment by kyrylomyr** [comment]
> For example, GHot.Register(Keys.A) doesn't work (Visual Basic jsyk), but how would this be done?

If you want to register the key without modifiers, just pass a `None` as a second parameter:

```
var manager = new HotKeyManager();
var hotKey = manager.Register(Key.A, System.Windows.Input.ModifierKeys.None);
```

> I need to hook a Key, who's Keycode is 255, and described according to windows as LButton, OemClear, how would I do this?

GlobalHotKey uses the [Keys](https://msdn.microsoft.com/en-us/library/system.windows.forms.keys%28v=vs.110%29.aspx) enumeration. I don't know what is LButton according to the list of all available Keys.
